### ISSUE TITLE
KeyError: 'g_state'

### ISSUE THREAD

**Issue by Pradur241** [agrimgupta92/sgan#108]
After finished training the model, i met this problem when i tried to use the evaluate_model to test the checkpoint file.
>Traceback (most recent call last):
  File "scripts/evaluate_model.py", line 117, in <module>
    main(args)
  File "scripts/evaluate_model.py", line 106, in main
    generator = get_generator(checkpoint)
  File "scripts/evaluate_model.py", line 38, in get_generator
    generator.load_state_dict(checkpoint['g_state'])
KeyError: 'g_state'

How can i solve the problem? Help please!

**Comment by Pradur241** [comment]
Problem solved. Use checkpoint_with_model.pt
