### ISSUE TITLE
invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces).

### ISSUE THREAD

**Issue by zeyayin** [agrimgupta92/sgan#22]
[INFO: train.py:  118]: Initializing train dataset
[INFO: train.py:  120]: Initializing val dataset
[INFO: train.py:  128]: There are 112.16666666666667 iterations per epoch
[INFO: train.py:  152]: Here is the generator:
[INFO: train.py:  153]: TrajectoryGenerator(
  (encoder): Encoder(
    (encoder): LSTM(64, 64)
    (spatial_embedding): Linear(in_features=2, out_features=64, bias=True)
  )
  (decoder): Decoder(
    (decoder): LSTM(64, 128)
    (pool_net): PoolHiddenNet(
      (spatial_embedding): Linear(in_features=2, out_features=64, bias=True)
      (mlp_pre_pool): Sequential(
        (0): Linear(in_features=192, out_features=512, bias=True)
        (1): ReLU()
        (2): Linear(in_features=512, out_features=1024, bias=True)
        (3): ReLU()
      )
    )
    (mlp): Sequential(
      (0): Linear(in_features=1152, out_features=1024, bias=True)
      (1): ReLU()
      (2): Linear(in_features=1024, out_features=128, bias=True)
      (3): ReLU()
    )
    (spatial_embedding): Linear(in_features=2, out_features=64, bias=True)
    (hidden2pos): Linear(in_features=128, out_features=2, bias=True)
  )
  (pool_net): PoolHiddenNet(
    (spatial_embedding): Linear(in_features=2, out_features=64, bias=True)
    (mlp_pre_pool): Sequential(
      (0): Linear(in_features=128, out_features=512, bias=True)
      (1): ReLU()
      (2): Linear(in_features=512, out_features=1024, bias=True)
      (3): ReLU()
    )
  )
  (mlp_decoder_context): Sequential(
    (0): Linear(in_features=1088, out_features=1024, bias=True)
    (1): ReLU()
    (2): Linear(in_features=1024, out_features=128, bias=True)
    (3): ReLU()
  )
)
[INFO: train.py:  168]: Here is the discriminator:
[INFO: train.py:  169]: TrajectoryDiscriminator(
  (encoder): Encoder(
    (encoder): LSTM(64, 64)
    (spatial_embedding): Linear(in_features=2, out_features=64, bias=True)
  )
  (real_classifier): Sequential(
    (0): Linear(in_features=64, out_features=1024, bias=True)
    (1): ReLU()
    (2): Linear(in_features=1024, out_features=1, bias=True)
    (3): ReLU()
  )
)
[INFO: train.py:  188]: Restoring from checkpoint C:\Users\zeya\sgan-master\checkpoint_with_model.pt
[INFO: train.py:  232]: Starting epoch 119

Traceback (most recent call last):
  File "scripts/train.py", line 580, in <module>
    main(args)
  File "scripts/train.py", line 245, in main
    optimizer_d)
  File "scripts/train.py", line 371, in discriminator_step
    generator_out = generator(obs_traj, obs_traj_rel, seq_start_end)
  File "C:\Users\zeya\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\zeya\sgan-master\scripts\sgan\models.py", line 508, in forward
    final_encoder_h = self.encoder(obs_traj_rel)
  File "C:\Users\zeya\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\zeya\sgan-master\scripts\sgan\models.py", line 63, in forward
    obs_traj_embedding = self.spatial_embedding(obs_traj.view(-1, 2))
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at c:\new-builder_3\win-wheel\pytorch\aten\src\th\generic/THTensor.cpp:237

**Comment by zeyayin** [comment]
Hello
I meet an issue when I try to train new model. I run it on wins with python 0.4.1 . I remove all the cuda() in order to run on cpu  but I meet this issue.

Have someone all meet same issue?

**Comment by angeliand** [comment]
Hi!
Could you provide the script you have run, so that the issue can be recreated?

**Comment by zeyayin** [comment]
> Hi!
> Could you provide the script you have run, so that the issue can be recreated?

I change my issue but not quite sure about your meaning of providing the script

**Comment by angeliand** [comment]
This was exactly what I wanted, thank you!
This is weird though, as it runs just fine for me. I would try different things if I were you:
*  you could try editing the code in [sgan\models.py line 63](https://github.com/agrimgupta92/sgan/blob/master/sgan/models.py#L63). to
`obs_traj_embedding = self.spatial_embedding(obs_traj.contiguous().view(-1, 2))` 
or
* you could install the exact [requirements ](https://github.com/agrimgupta92/sgan/blob/master/requirements.txt), as this can cause problems too.

**Comment by zeyayin** [comment]
After I change the model.py line 63 and run this command !python scripts/train.py --noise_dim=
It just keep running or even got stuck without giving any response.
I will try it on desktop PC later.

**Comment by zeyayin** [comment]
> 
> 
> This was exactly what I wanted, thank you!
> This is weird though, as it runs just fine for me. I would try different things if I were you:
> 
>     * you could try editing the code in [sgan\models.py line 63](https://github.com/agrimgupta92/sgan/blob/master/sgan/models.py#L63). to
>       `obs_traj_embedding = self.spatial_embedding(obs_traj.contiguous().view(-1, 2))`
>       or
> 
>     * you could install the exact [requirements ](https://github.com/agrimgupta92/sgan/blob/master/requirements.txt), as this can cause problems too.

Hello after I add the contiguous() and run on destop, it begins to ask for updating of cuda driver version even I have delete all cuda(). Is there anyway I can run on CPU instead of gpu

**Comment by xieshuaix** [comment]
The issue arises from permuting mini-batch in seq_collate(data) of the data loader; tensor.permute breaks contiguity of a tensor and calling view on it raises an error.Training and testing on GPU are not subject to this issue because tensor.cuda() automatically makes the tensor contiguous. These can be seen from below:

obs_traj.view(-1, 2).shape = {RuntimeError}invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /pytorch/aten/src/TH/generic/THTensor.cpp:213
obs_traj.numpy().strides = {tuple} <class 'tuple'>: (4, 64, 32)
obs_traj.contiguous().view(-1, 2).shape = {Size} torch.Size([1304, 2])
obs_traj.contiguous().numpy().strides = {tuple} <class 'tuple'>: (1304, 8, 4)
obs_traj.cuda().cpu().numpy().shape = {tuple} <class 'tuple'>: (8, 163, 2)
obs_traj.cuda().cpu().numpy().strides = {tuple} <class 'tuple'>: (1304, 8, 4)
obs_traj.reshape(-1, 2).numpy().shape = {tuple} <class 'tuple'>: (1304, 2)
obs_traj.reshape(-1, 2).numpy().strides = {tuple} <class 'tuple'>: (8, 4)

**Comment by davidglavas** [comment]
In models.py:

- change line ~67 to: 
`obs_traj_embedding = self.spatial_embedding(obs_traj.contiguous().view(-1, 2))`
- change line ~221 to: 
`curr_hidden = h_states.contiguous().view(-1, self.h_dim)[start:end]`

This resolved the issue for me.
