### ISSUE TITLE
Why did I encounter such a mistake?

### ISSUE THREAD

**Issue by DENGZAIXU** [agrimgupta92/sgan#43]
This error occurred when I ran ‘script/train.py’

[INFO: train.py:  119]: Initializing train dataset
[INFO: train.py:  121]: Initializing val dataset
[INFO: train.py:  129]: There are 21.03125 iterations per epoch
Traceback (most recent call last):
  File "scripts/train.py", line 581, in <module>
    main(args)
  File "scripts/train.py", line 149, in main
    batch_norm=args.batch_norm)
  File "/home/xu/dengzaixu/sgan/sgan/models.py", line 425, in __init__
    if self.noise_dim[0] == 0:
TypeError: 'NoneType' object is not subscriptable

**Comment by DENGZAIXU** [comment]
I have solved this mistake.

**Comment by renegaderl** [comment]
> I have solved this mistake.

I have the same problem and I'm confused. So how did u solve the problem?

**Comment by dim-fate** [comment]
batch_norm=None，so batch_norm[0] is inexistent.

**Comment by YueWang72** [comment]
> I have solved this mistake.
I have the same problem.Can you tell me how ti solve it?

**Comment by cxc1219** [comment]
> I have solved this mistake.

Can you tell me how to solve the problem? thanks very much
