### ISSUE TITLE
During training: "ValueError: could not convert string to float" because of delimiters

### ISSUE THREAD

**Issue by axem20** [agrimgupta92/sgan#52]
"ValueError: could not convert string to float: '0.0\t1.0\t11.238836854\t3.746958' "

As you can see, the delimiters are set to \t and so the data becomes a string which cannot be converted to float. Could you recommend how this should be working instead?

**Comment by gwiplot** [comment]
change dlim to '\t' in the error part

**Comment by haishi-ai** [comment]
if you use delimiters with tab, set --delim="tab".

``` code
python3 scripts/train.py --delim="tab"
```
> doesn't work --delim='\t' (default)

**Comment by Hahaemmm** [comment]
> if you use delimiters with tab, set --delim="tab".
> 
> ```
> python3 scripts/train.py --delim="tab"
> ```
> 

when i use ‘--delim="tab"’ ，it presents the following problem: 

Traceback (most recent call last):
  File "scripts/train.py", line 582, in <module>
    main(args)
  File "scripts/train.py", line 150, in main
    batch_norm=args.batch_norm)
  File "/home/caixianchen/sgan/sgan/models.py", line 425, in __init__
    if self.noise_dim[0] == 0:
TypeError: 'NoneType' object is not subscriptable

**Comment by haishi-ai** [comment]
> if self.noise_dim[0] == 0:
> TypeError: 'NoneType' object is not subscriptable

this is another problem.

i add the following option.  
>--noise_dim=0

NoneType(defalut value) is not tupple. doesnt work.. 
defalut value is not correct. unbelievable.

[total command]
``` command
$ python scripts/train.py --delim="tab" --noise_dim=0
```

**Comment by Yinan-x-Zhang** [comment]
I think is this!   
#line = line.strip().split(delim)
   line = re.split('\s+',line.strip())
