### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by fengxianghu** [agrimgupta92/sgan#91]
I have met the problem, when I run my the train.py.

Traceback (most recent call last):
  File "train.py", line 595, in <module>
    main(args)
  File "train.py", line 160, in main
    batch_norm=args.batch_norm)
  File "/content/gdrive/MyDrive/SGAN/sgan/models.py", line 492, in __init__
    if self.noise_dim[0] == 0:
TypeError: 'NoneType' object is not subscriptable

Has any friend met this problem and solved it?

**Comment by rjycty** [comment]
Friend, I have the same problem. Have you solved it now?

**Comment by fengxianghu** [comment]
> Friend, I have the same problem. Have you solved it now?

I remember I have solved this problem with a answer under a previous issue. You can try it.

**Comment by rjycty** [comment]
Thanks！

**Comment by cghaon** [comment]
how did you solve it? I got same problem= = I think it is about the size of noise, but I do not totally understand how noise works.

**Comment by rjycty** [comment]
> how did you solve it? I got same problem= = I think it is about the size of noise, but I do not totally understand how noise works.

train.py line53 (It may not be line 53, but it must contain '--noise_dim' )
change None to (0,)

**Comment by Mogalipen** [comment]
Try to change the codes
![image](https://user-images.githubusercontent.com/61398854/167269309-8ccfd320-473f-42f4-a1ce-8a3e263e52ef.png)
to
![image](https://user-images.githubusercontent.com/61398854/167269255-9b5a4547-d865-43bd-8ce3-fa8ab41dae4e.png)
It will work and you can use '--noise_dim'  option.
If I'm wrong, just tell me.
I'm a junior.

**Comment by neugzy** [comment]
> > how did you solve it? I got same problem= = I think it is about the size of noise, but I do not totally understand how noise works.
> 
> train.py line53 (It may not be line 53, but it must contain '--noise_dim' ) change None to (0,)

It is line 52 actually.
